"""Initial database schema

Revision ID: 29bf064c68b7
Revises: 
Create Date: 2025-11-21 20:47:31.510492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29bf064c68b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'CREATOR', 'MASTER', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', name='subscriptionstatus'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_ai_images_used', sa.Integer(), nullable=True),
    sa.Column('monthly_ai_players_used', sa.Integer(), nullable=True),
    sa.Column('pdf_imports_count', sa.Integer(), nullable=True),
    sa.Column('quota_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dm_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', 'INVITE_ONLY', name='campaignvisibility'), nullable=False),
    sa.Column('rule_system', sa.String(length=100), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_session_number', sa.Integer(), nullable=True),
    sa.Column('ai_dm_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_dm_personality', sa.String(length=50), nullable=True),
    sa.Column('ai_players_enabled', sa.Boolean(), nullable=True),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('current_chapter', sa.String(length=200), nullable=True),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_s3_key', sa.String(length=500), nullable=True),
    sa.Column('archive_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dm_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('character_type', sa.Enum('PLAYER', 'NPC', 'AI_PLAYER', name='charactertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('character_class', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('background', sa.String(length=100), nullable=True),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('ability_scores', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('saving_throws', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('temp_hp', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('initiative_bonus', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('proficiencies', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('spells', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('personality_traits', sa.Text(), nullable=True),
    sa.Column('ideals', sa.Text(), nullable=True),
    sa.Column('bonds', sa.Text(), nullable=True),
    sa.Column('flaws', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('token_url', sa.String(length=500), nullable=True),
    sa.Column('ai_personality', sa.String(length=50), nullable=True),
    sa.Column('ai_behavior_prompt', sa.Text(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('dm_notes', sa.Text(), nullable=True),
    sa.Column('player_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='sessionstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('current_scene', sa.String(length=200), nullable=True),
    sa.Column('current_map_id', sa.UUID(), nullable=True),
    sa.Column('active_combatants', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ai_requests_count', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('ai_images_generated', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_events', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('npcs_met', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('items_found', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('quests_updated', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('image_type', sa.Enum('CHARACTER', 'NPC', 'ITEM', 'SCENE', 'MONSTER', name='imagetype'), nullable=False),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_campaign_id'), 'generated_images', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_generated_images_created_at'), 'generated_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_images_created_by'), 'generated_images', ['created_by'], unique=False)
    op.create_index(op.f('ix_generated_images_image_type'), 'generated_images', ['image_type'], unique=False)
    op.create_index(op.f('ix_generated_images_related_id'), 'generated_images', ['related_id'], unique=False)
    op.create_table('generated_maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('map_type', sa.Enum('BATTLE', 'WORLD', 'DUNGEON', 'INTERIOR', name='maptype'), nullable=False),
    sa.Column('grid_type', sa.String(length=20), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('map_metadata', sa.JSON(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_maps_campaign_id'), 'generated_maps', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_generated_maps_created_at'), 'generated_maps', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_maps_created_by'), 'generated_maps', ['created_by'], unique=False)
    op.create_index(op.f('ix_generated_maps_map_type'), 'generated_maps', ['map_type'], unique=False)
    op.create_table('campaign_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('DM', 'PLAYER', 'OBSERVER', name='memberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_members_campaign_id'), 'campaign_members', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_members_user_id'), 'campaign_members', ['user_id'], unique=False)
    op.create_table('character_effects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effect_type', sa.Enum('BUFF', 'DEBUFF', 'CONDITION', name='effecttype'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('duration_type', sa.String(length=20), nullable=True),
    sa.Column('duration_remaining', sa.Integer(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_effects_character_id'), 'character_effects', ['character_id'], unique=False)
    op.create_table('session_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_logs_created_at'), 'session_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_logs_log_type'), 'session_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_session_logs_session_id'), 'session_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_logs_session_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_log_type'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_created_at'), table_name='session_logs')
    op.drop_table('session_logs')
    op.drop_index(op.f('ix_character_effects_character_id'), table_name='character_effects')
    op.drop_table('character_effects')
    op.drop_index(op.f('ix_campaign_members_user_id'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_campaign_id'), table_name='campaign_members')
    op.drop_table('campaign_members')
    op.drop_index(op.f('ix_generated_maps_map_type'), table_name='generated_maps')
    op.drop_index(op.f('ix_generated_maps_created_by'), table_name='generated_maps')
    op.drop_index(op.f('ix_generated_maps_created_at'), table_name='generated_maps')
    op.drop_index(op.f('ix_generated_maps_campaign_id'), table_name='generated_maps')
    op.drop_table('generated_maps')
    op.drop_index(op.f('ix_generated_images_related_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_image_type'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_created_by'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_created_at'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_campaign_id'), table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_table('game_sessions')
    op.drop_table('characters')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
